"""
analysis.py — Core pallor/erythema colour analysis.

This module provides two classification paths:

1. ML-based (primary): Loads a pre-trained Random Forest model
   (model_rf.pkl generated by train_model.py) and classifies the
   palpebral conjunctiva ROI using colour features.

2. Rule-based (fallback): The original threshold-based classifier
   used when no trained model is available.

For real-world images uploaded via the app the module automatically
extracts the palpebral conjunctiva ROI (the lower-eyelid strip) from
the full eye photo before feature extraction.
"""

import os
import pickle
import logging
from pathlib import Path

import cv2
import numpy as np

logger = logging.getLogger(__name__)

# ─── ROI constants (used when analysing full eye photos) ──────────────────
# Matches the on-screen capture guide in the frontend prototype.
ROI_TOP = 0.30
ROI_LEFT = 0.38
ROI_W = 0.24
ROI_H = 0.24

# ─── Anemia severity labels (must match train_model.py CLASS_LABELS) ──────
CLASS_LABELS = ["Anemic", "Mild", "Normal"]

# ─── Human-readable guidance per severity band ────────────────────────────
BAND_GUIDANCE = {
    "Normal": "Conjunctiva colour is within the expected healthy range. No elevated anaemia risk detected in this screen.",
    "Mild":   "Slight pallor detected. Re-screen in better lighting; if it persists, a routine blood test is a good idea.",
    "Anemic": "Noticeable pallor detected. Haemoglobin is likely below 11 g/dL. We recommend confirming with a clinical blood test soon.",
}

# ─── Model loading ────────────────────────────────────────────────────────

_MODEL_BUNDLE: dict | None = None
_MODEL_LOADED: bool = False   # True once we've attempted to load (avoids repeated attempts)

def _find_model_file() -> str | None:
    """Look for model_rf.pkl next to this file or in the current working directory."""
    candidates = [
        Path(__file__).parent / "model_rf.pkl",
        Path("model_rf.pkl"),
    ]
    for p in candidates:
        if p.is_file():
            return str(p)
    return None


def load_model(path: str | None = None) -> bool:
    """
    Load the trained Random Forest model bundle.

    Returns True if the model was loaded successfully, False otherwise.
    Call this once at startup; the module caches the result.
    """
    global _MODEL_BUNDLE, _MODEL_LOADED
    if _MODEL_LOADED:
        return _MODEL_BUNDLE is not None

    _MODEL_LOADED = True
    model_path = path or _find_model_file()
    if model_path is None:
        logger.warning("model_rf.pkl not found — falling back to rule-based classifier.")
        return False

    try:
        with open(model_path, "rb") as f:
            bundle = pickle.load(f)
        _MODEL_BUNDLE = bundle
        acc = bundle.get("test_accuracy", "?")
        cv = bundle.get("cv_mean", "?")
        logger.info(
            "Loaded RF model from %s (CV acc=%.3f, test acc=%.3f)",
            model_path, cv if isinstance(cv, float) else 0, acc if isinstance(acc, float) else 0,
        )
        return True
    except Exception as exc:
        logger.error("Failed to load model_rf.pkl: %s — using rule-based fallback.", exc)
        return False


def is_ml_available() -> bool:
    """Return True if the ML model is loaded and ready."""
    return _MODEL_BUNDLE is not None


# ─── ROI extraction ───────────────────────────────────────────────────────

def extract_roi(image_bgr: np.ndarray) -> np.ndarray:
    """Crop the palpebral conjunctiva ROI from a full eye photograph."""
    h, w = image_bgr.shape[:2]
    x0 = int(w * ROI_LEFT)
    y0 = int(h * ROI_TOP)
    x1 = x0 + int(w * ROI_W)
    y1 = y0 + int(h * ROI_H)
    x1, y1 = min(x1, w), min(y1, h)
    return image_bgr[y0:y1, x0:x1]


# ─── Feature extraction (shared by training and inference) ───────────────

def extract_colour_features(roi_bgr: np.ndarray, mask_white: bool = True) -> np.ndarray:
    """
    Extract 18 colour features from a BGR image (or ROI crop).

    If mask_white=True, white-background pixels (all channels > 240) are
    excluded so we only analyse conjunctiva tissue — this matches the
    training procedure in train_model.py.

    If mask_white=False (whole ROI from a live eye photo), all pixels
    are included.
    """
    if mask_white:
        white_mask = np.all(roi_bgr > 240, axis=2)
        tissue_mask = ~white_mask
    else:
        tissue_mask = np.ones(roi_bgr.shape[:2], dtype=bool)

    tissue_count = int(tissue_mask.sum())
    if tissue_count < 50:
        raise ValueError("Insufficient tissue pixels in ROI — image may be overexposed or too small.")

    tissue_bgr = roi_bgr[tissue_mask].astype(np.float64)
    b_px, g_px, r_px = tissue_bgr[:, 0], tissue_bgr[:, 1], tissue_bgr[:, 2]

    # RGB stats
    mean_r, mean_g, mean_b = r_px.mean(), g_px.mean(), b_px.mean()
    std_r, std_g, std_b = r_px.std(), g_px.std(), b_px.std()

    # HSV stats
    roi_hsv = cv2.cvtColor(roi_bgr, cv2.COLOR_BGR2HSV)
    tissue_hsv = roi_hsv[tissue_mask].astype(np.float64)
    h_px = tissue_hsv[:, 0] * (360.0 / 180.0)
    s_px = tissue_hsv[:, 1] / 255.0
    v_px = tissue_hsv[:, 2] / 255.0

    mean_h, mean_s, mean_v = h_px.mean(), s_px.mean(), v_px.mean()
    std_h, std_s, std_v = h_px.std(), s_px.std(), v_px.std()

    # Colour ratios
    eps = 1e-6
    rg_ratio = mean_r / (mean_g + eps)
    rb_ratio = mean_r / (mean_b + eps)
    gb_ratio = mean_g / (mean_b + eps)

    # Derived pallor features
    erythema_index = ((mean_r - (mean_g + mean_b) / 2.0) / 255.0) * (0.5 + mean_s)
    pallor_score = max(0.0, min(1.0, 0.5 - erythema_index))

    # Tissue area fraction (0-1)
    total_px = roi_bgr.shape[0] * roi_bgr.shape[1]
    area_fraction = tissue_count / max(total_px, 1)

    return np.array([
        mean_r, mean_g, mean_b,
        std_r, std_g, std_b,
        mean_h, mean_s, mean_v,
        std_h, std_s, std_v,
        rg_ratio, rb_ratio, gb_ratio,
        erythema_index, pallor_score,
        area_fraction,
    ], dtype=np.float32)


# ─── Public API ───────────────────────────────────────────────────────────

def compute_features(image_bytes: bytes) -> dict:
    """
    Decode an uploaded image and compute pallor/erythema features.

    Returns a dict with avg_r, avg_g, avg_b, saturation, value,
    erythema_index, pallor_score — same keys as before so the API
    response shape is unchanged.
    """
    arr = np.frombuffer(image_bytes, dtype=np.uint8)
    img_raw = cv2.imdecode(arr, cv2.IMREAD_UNCHANGED)
    if img_raw is None:
        raise ValueError("Could not decode image")

    # Composite RGBA images onto white so transparent regions become white
    # and are correctly excluded by the white-pixel mask below.
    if img_raw.ndim == 3 and img_raw.shape[2] == 4:
        alpha = img_raw[:, :, 3:4].astype(np.float64) / 255.0
        bgr = img_raw[:, :, :3].astype(np.float64)
        img_bgr = (bgr * alpha + 255.0 * (1.0 - alpha)).astype(np.uint8)
    elif img_raw.ndim == 2:
        img_bgr = cv2.cvtColor(img_raw, cv2.COLOR_GRAY2BGR)
    else:
        img_bgr = img_raw

    # Decide whether image is a pre-cropped conjunctiva (has white/transparent bg)
    # or a full eye photo. Heuristic: if > 30% of pixels are near-white, treat as pre-cropped.
    white_frac = float(np.all(img_bgr > 240, axis=2).mean())
    is_precropped = white_frac > 0.30

    if is_precropped:
        roi = img_bgr
        mask_white = True
    else:
        roi = extract_roi(img_bgr)
        if roi.size == 0:
            raise ValueError("ROI is empty — image too small")
        mask_white = False

    feats = extract_colour_features(roi, mask_white=mask_white)

    mean_r, mean_g, mean_b = float(feats[0]), float(feats[1]), float(feats[2])
    mean_s = float(feats[7])
    mean_v = float(feats[8])
    erythema_index = float(feats[15])
    pallor_score = float(feats[16])

    return {
        "avg_r": mean_r,
        "avg_g": mean_g,
        "avg_b": mean_b,
        "saturation": mean_s,
        "value": mean_v,
        "erythema_index": erythema_index,
        "pallor_score": pallor_score,
        # Store the full feature vector for ML inference
        "_colour_features": feats,
    }


def ml_classify(features: dict) -> dict:
    """
    Classify anemia severity using the loaded Random Forest model.

    `features` is the dict returned by compute_features().
    Returns a result dict with keys: band, guidance, method, confidence.
    """
    if not is_ml_available():
        return rule_based_band(features["pallor_score"])

    bundle = _MODEL_BUNDLE
    pipeline = bundle["pipeline"]
    feat_vec = features.get("_colour_features")
    if feat_vec is None:
        return rule_based_band(features["pallor_score"])

    X = feat_vec.reshape(1, -1)
    try:
        label = pipeline.predict(X)[0]
        proba = pipeline.predict_proba(X)[0]
        confidence = float(proba.max())
        classes = pipeline.classes_
        proba_dict = {str(c): round(float(p), 3) for c, p in zip(classes, proba)}
    except Exception as exc:
        logger.error("ML inference failed: %s — falling back to rule-based.", exc)
        return rule_based_band(features["pallor_score"])

    return {
        "band": label,
        "guidance": BAND_GUIDANCE.get(label, ""),
        "method": "random_forest_v1",
        "confidence": round(confidence, 3),
        "probabilities": proba_dict,
    }


# ─── Rule-based fallback (kept for compatibility) ─────────────────────────

RULE_THRESHOLDS = [
    (0.38, "Normal", BAND_GUIDANCE["Normal"]),
    (0.47, "Mild",   BAND_GUIDANCE["Mild"]),
    (1.01, "Anemic", BAND_GUIDANCE["Anemic"]),
]


def rule_based_band(pallor_score: float) -> dict:
    for threshold, label, guidance in RULE_THRESHOLDS:
        if pallor_score < threshold:
            return {"band": label, "guidance": guidance, "method": "rule_based", "confidence": None}
    return {"band": "Anemic", "guidance": BAND_GUIDANCE["Anemic"], "method": "rule_based", "confidence": None}
