import { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API_URL = import.meta.env.VITE_API_URL?.replace(/\/$/, '');
const guidance = { Normal: 'No elevated risk was detected in this screening. This does not rule out anaemia.', Mild: 'Re-screen in even lighting. If pallor persists, arrange a routine haemoglobin blood test.', Anemic: 'Noticeable pallor detected. Haemoglobin is likely below 11 g/dL. Please arrange a clinical blood test soon.' };
function hsv(r,g,b) { r/=255; g/=255; b/=255; const max=Math.max(r,g,b), min=Math.min(r,g,b); return {s:max===0?0:(max-min)/max,v:max}; }
function localAnalysis(image) {
  const canvas=document.createElement('canvas'), width=image.naturalWidth||image.videoWidth, height=image.naturalHeight||image.videoHeight;
  canvas.width=width; canvas.height=height; const context=canvas.getContext('2d',{willReadFrequently:true}); context.drawImage(image,0,0,width,height);
  const x=Math.floor(width*.38),y=Math.floor(height*.30),pixels=context.getImageData(x,y,Math.floor(width*.24),Math.floor(height*.24)).data;
  let r=0,g=0,b=0,saturation=0,value=0,count=0; for(let i=0;i<pixels.length;i+=4){r+=pixels[i];g+=pixels[i+1];b+=pixels[i+2];const c=hsv(pixels[i],pixels[i+1],pixels[i+2]);saturation+=c.s;value+=c.v;count++;}
  const avg_r=r/count,avg_g=g/count,avg_b=b/count,sat=saturation/count,val=value/count,erythema_index=((avg_r-(avg_g+avg_b)/2)/255)*(.5+sat),pallor_score=Math.max(0,Math.min(1,.5-erythema_index));
  const band=pallor_score<.38?'Normal':pallor_score<.47?'Mild':'Anemic';
  return {features:{avg_r,avg_g,avg_b,saturation:sat,value:val,erythema_index,pallor_score},result:{band,guidance:guidance[band],method:'on_device_rule_based',confidence:null}};
}
function bandClass(band) { return band==='Normal'?'normal':band==='Mild'?'mild':'anemic'; }
function Result({data}) { const f=data.features,r=data.result; return <><div className={`band ${bandClass(r.band)}`}>{r.band}{r.confidence!=null&&<span style={{fontSize:'12px',marginLeft:'8px',opacity:0.75}}>({Math.round(r.confidence*100)}% conf)</span>}</div><dl>{r.hgb_estimate!=null&&<><dt>Estimated Hgb</dt><dd>{r.hgb_estimate} g/dL</dd></>}<dt>Pallor score</dt><dd>{f.pallor_score.toFixed(3)}</dd><dt>Erythema index</dt><dd>{f.erythema_index.toFixed(3)}</dd><dt>RGB mean</dt><dd>{Math.round(f.avg_r)}, {Math.round(f.avg_g)}, {Math.round(f.avg_b)}</dd><dt>Method</dt><dd>{r.method.replaceAll('_',' ')}</dd></dl><p className="advice">{r.guidance}</p></>; }
function App() {
  const video=useRef(null),stream=useRef(null); const [consented,setConsented]=useState(false),[preview,setPreview]=useState(null),[imageSource,setImageSource]=useState(null),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Start the camera or upload a photo.');
  useEffect(()=>()=>stream.current?.getTracks().forEach(t=>t.stop()),[]);
  useEffect(()=>{if(preview==='camera'&&video.current&&stream.current)video.current.srcObject=stream.current;},[preview]);
  async function startCamera(){try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'}});setPreview('camera');setMessage('Align the lower eyelid inside the guide, then capture.');}catch{setMessage('Camera permission is unavailable. Use Upload photo instead.');}}
  function showImage(source){const captured=new Image();captured.onload=()=>{stream.current?.getTracks().forEach(t=>t.stop());setImageSource(source);setPreview('image');runAnalysis(captured);};captured.src=source;}
  function capture(){const c=document.createElement('canvas');c.width=video.current.videoWidth;c.height=video.current.videoHeight;c.getContext('2d').drawImage(video.current,0,0);showImage(c.toDataURL('image/png'));}
  function upload(e){const file=e.target.files?.[0];if(file)showImage(URL.createObjectURL(file));}
  async function runAnalysis(captured){setBusy(true);setMessage('Analysing the guided region…');try{if(!API_URL){setResult(localAnalysis(captured));setMessage('Processed on this device.');return;}const c=document.createElement('canvas');c.width=captured.naturalWidth;c.height=captured.naturalHeight;c.getContext('2d').drawImage(captured,0,0);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png')),body=new FormData();body.append('file',blob,'capture.png');const response=await fetch(`${API_URL}/analyze`,{method:'POST',body});if(!response.ok)throw Error();setResult(await response.json());setMessage('Processed by the secure API.');}catch{setResult(localAnalysis(captured));setMessage('API unavailable; processed on this device.');}finally{setBusy(false);}}
  function reset(){stream.current?.getTracks().forEach(t=>t.stop());setPreview(null);setImageSource(null);setResult(null);setMessage('Start the camera or upload a photo.');}
  return <main className="shell"><header><div><span className="mark">A</span><strong>AnemiaScan</strong><small>Omni_BioTech_2 · Prototype</small></div><span className="pill">PWA · privacy-first</span></header><section className="intro"><p className="eyebrow">NON-INVASIVE SCREENING</p><h1>Camera-assisted conjunctiva pallor screening</h1><p>Use the guided capture to get a preliminary risk band. It is a screening aid—not a diagnosis or replacement for a haemoglobin blood test.</p></section>{!consented?<section className="consent card"><h2>Before you begin</h2><p>Your image is analysed on this device by default and is not saved. If the deployed API is enabled, it is sent once for in-memory analysis and then discarded. Do not use this result for emergency decisions.</p><label><input type="checkbox" onChange={e=>setConsented(e.target.checked)}/> I understand and consent to this screening.</label></section>:<><section className="grid"><section className="card"><h2>1 · Guided capture</h2><div className="stage">{preview==='camera'&&<video ref={video} autoPlay playsInline muted/>}{preview==='image'&&<img src={imageSource} alt="Captured conjunctiva"/>}<div className="guide"><span>align lower eyelid here</span></div>{!preview&&<p>Camera preview appears here</p>}</div><p className="hint">{message}</p><div className="actions"><button onClick={startCamera}>Start camera</button><button disabled={preview!=='camera'} onClick={capture}>Capture</button><label className="button secondary">Upload photo<input type="file" accept="image/*" onChange={upload}/></label><button className="secondary" onClick={reset}>Reset</button></div></section><section className="card"><h2>2 · Screening result</h2>{busy&&<p>Analysing…</p>}{result?<Result data={result}/>:<p className="muted">Your risk band and colour features will appear after capture.</p>}<p className="warning"><strong>Not a diagnosis.</strong> An elevated result must be confirmed with a clinical haemoglobin blood test.</p></section></section><section className="steps"><article><b>OpenCV API</b><span>Optional FastAPI route extracts the same ROI and colour features.</span></article><article><b>On-device fallback</b><span>Works without connectivity; image capture is not stored.</span></article><article><b>Model roadmap</b><span>Clinical validation and a real TFLite model are required before health use.</span></article></section></>}</main>;
}
createRoot(document.getElementById('root')).render(<App/>);
